---
- name: Create root.key file
  copy:
    dest: /tmp/root.key
    content: "{{ ca_root_key }}"
  run_once: true

- name: Create root.crt file
  copy:
    dest: /tmp/root.crt
    content: "{{ ca_root_crt }}"
  run_once: true

- name: Generate an OpenSSL private key with the default values (4096 bits, RSA)
  community.crypto.openssl_privatekey:
    path: "{{ generate_cert_key_path }}"

- name: Generate an OpenSSL Certificate Signing Request with subjectAltName extension
  community.crypto.openssl_csr:
    path: "{{ generate_cert_csr_path }}"
    privatekey_path: "{{ generate_cert_key_path }}"
    common_name: "{{ generate_cert_common_name }}"
    subject_alt_name: "{{ generate_cert_subject_alt_name | default(omit) }}"
  register: csr

- name: Generate an OpenSSL certificate signed with your own CA certificate
  openssl_certificate:
    path: "{{ generate_cert_crt_path }}"
    csr_path: "{{ generate_cert_csr_path }}"
    ownca_path: /tmp/root.crt
    ownca_privatekey_path: /tmp/root.key
    ownca_privatekey_passphrase: "{{ generate_cert_root_ca_pwd }}"
    provider: ownca
    force: yes
